<?php
/**
 * @category    Ktpl
 * @package     Ktpl_BetterPopup
 */

/** @var \Ktpl\BetterPopup\Block\Adminhtml\System\Config\Button $block */
?>
<div class="actions actions-test-email">
    <button class="actions-test-email" type="button" id="<?= /** @noEscape */ $block->getHtmlId() ?>">
        <span><?= /** @noEscape */ $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'Magento_Ui/js/modal/alert',
        "mage/translate"
    ], function ($, alert, $t) {
        $('#betterpopup_send_email_sent').click(function () {
            $.ajax({
                url: "<?= /** @noEscape */ $block->getUrl('mpbetterpopup/send/send', ['form_key' => $block->getFormKey(), '_current' => true]) ?>",
                dataType: 'json',
                showLoader: true,
                success: function (result) {
                    alert({
                        title: result.status ? $t('Success') : $t('Error'),
                        content: result.content ? result.content : result
                    });
                }
            });
        })
    });
</script>
