<?php
/**
 * @category  Ktpl
 * @package   Ktpl_SocialLogin
 */
?>
<?php if ($block->isEnabled() && $block->isEnabled() === 'popup_login') : ?>
    <div id="social-login-popup" class="white-popup mfp-with-anim mfp-hide"
         data-mage-init='{"socialPopupForm": <?= $block->getFormParams() ?>}'>
        <?= $block->getChildHtml('popup.email') ?>
        <?= $block->getChildHtml('popup.authentication') ?>
        <?= $block->getChildHtml('popup.create') ?>
        <?= $block->getChildHtml('popup.forgot') ?>
        <?= $block->getChildHtml('popup.additional.info') ?>
    </div>
    <div style="clear: both"></div>
<?php endif; ?>




