<?php
/**
 * @category  Ktpl
 * @package   Ktpl_SocialLogin
 */

use Ktpl\SocialLogin\Model\System\Config\Source\Position;

?>
<?php $availableSocials = $block->getAvailableSocials(); ?>
<?php if ($block->canShow(Position::PAGE_POPUP) && sizeof($availableSocials)) : ?>
    <div class="block social-login-authentication-channel col-mp mp-5">
        <div class="block-title">
            <?= __('Or Sign In With') ?>
        </div>
        <div class="block-content">
            <?php foreach ($availableSocials as $key => $social) : ?>
                <div class="actions-toolbar social-btn <?= $key ?>-login">
                    <a class="btn btn-block btn-social btn-<?= $block->getBtnKey($key) ?>"
                       data-mage-init='{"socialProvider": {"url": "<?= $social['login_url'] ?>", "label": "<?= __('Login By %1', $social['label']) ?>"}}'>
                        <span class="fa fa-<?= $block->getBtnKey($key) ?>"></span>
                        <?= __('Sign in with %1', $social['label']) ?>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <script type="text/javascript">
        require(['jquery'], function ($) {
            $('#social-login-authentication').removeClass('mp-12').addClass('mp-7');
        });
    </script>
<?php endif; ?>

<?php
/**
 * Add variable to show social buttons on customer authentication popup
 */
?>
<?php $authenConfig = $block->getSocialButtonsConfig(); ?>
<?php if ($block->canShow(Position::PAGE_AUTHEN) && sizeof($availableSocials)) : ?>
    <script>
        window.socialAuthenticationPopup = <?= Zend_Json::encode($authenConfig); ?>;
    </script>
<?php endif; ?>
