<?php
/**
 * @category    Ktpl
 * @package     Ktpl_BetterPopup
 */

$storeId         = $this->helper(\Ktpl\BetterPopup\Helper\Data::class)->getStoreId();
$subscriberToday = $block->getSubscriberToday() ? $block->getSubscriberToday()->getSize() : 0;
$subscriberWeek  = $block->getSubscriberInWeek() ? $block->getSubscriberInWeek($storeId)->getSize() : 0;
$subscriberMonth = $block->getSubscriberInMonth() ? $block->getSubscriberInMonth()->getSize() : 0;
?>
<div class="dashboard-item-container">
    <div class="dashboard-item-title"><?= /** @noEscape */ __('Subscribers') ?></div>
    <div class="dashboard-item-content">
        <table class="dashboard-data">
            <thead>
            <tr>
                <th><span><?= /** @noEscape */ __('Today') ?></span></th>
                <th><span><?= /** @noEscape */ __('Week') ?></span></th>
                <th><span><?= /** @noEscape */ __('Month') ?></span></th>
            </tr>
            </thead>
            <tbody style="text-align: center;">
            <tr>
                <td><span><?= /** @noEscape */ $subscriberToday ?></span></td>
                <td><span><?= /** @noEscape */ $subscriberWeek ?></span></td>
                <td><span><?= /** @noEscape */ $subscriberMonth ?></span></td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
