<?php
/**
 *
 * @category   Krish
 * @package    Ktpl_Quickview
 * @author     Extension Team
 */
?>
<?php $product = $block->getProduct(); ?>
<?php 
    $helper = $block->getHelper();
    $removeReview = $helper->getRemoveReview();
    $removeMoreInfo = $helper->getRemoveMoreInfo();
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Ktpl_Quickview/js/ktpl_beforebodyend": {
                "removeReview": "<?php echo $removeReview; ?>",
                "removeMoreInfo": "<?php echo $removeMoreInfo; ?>"
            }
        }
    }
</script>
