<?php
/**
 *
 * @category   Krish
 * @package    Ktpl_Quickview
 * @author     Extension Team
 */
?>
<?php
$helper = $this->helper('Ktpl\Quickview\Helper\Data');
$btnTextColor = $helper->getBtnTextColor();
$baseUrl = $helper->getBaseUrl();
$buttonText = $helper->getButtonText();
$btnBackground = $helper->getBtnBackground();
list($r, $g, $b) = sscanf($btnBackground, "%02x%02x%02x");
$productUrl = $helper->getUrl();
$buttonText = $helper->getButtonText();
$isEnabled = $helper->enabled();
$productItemInfo = $helper->getProductItemInfo();
$productImageWrapper = $helper->getProductImageWrapper();
?>

<style>
    a.ktpl-quickview{
        color: #<?php echo $btnTextColor; ?>;
        background-color: rgba(<?php echo "$r , $g , $b"; ?>,0.6);
    }
    a.ktpl-quickview {
        position: absolute;
        display: block;
        bottom: 0px;
        padding: 3px 10px;
        margin-left: auto;
        margin-right: auto;
        left: 0;
        right: 0;
        }
    .product-item .product-item-info:hover .ktpl-quickview{
        display: block !important;
        position: absolute !important;
        bottom: 0px !important;
        left: 0px !important;
        margin: 0;
        z-index: 99999999999999 !important;
        width: 100% !important;
        padding: 10px 0 10px 0;
        text-align: center !important;
        font-size: 14px !important;
        text-decoration: none !important;
    }

    .product-item .product-item-info:hover .ktpl-quickview{
        display: block !important;
        position: absolute !important;
        bottom: 0px !important;
        left: 0px !important;
        margin: 0;
        z-index: 99999999999999 !important;
        width: 100% !important;
        padding: 10px 0 10px 0;
        text-align: center !important;
        font-size: 14px !important;
        text-decoration: none !important;
    }
    .product-item .ktpl-quickview {display: none !important}
    #shopping-cart-table .ktpl-quickview {display: none !important}
    .products-related .product-item-info:hover .ktpl-quickview, .products-upsell .product-item-info:hover .ktpl-quickview {display: none !important}
</style>
<script type="text/x-magento-init">
    {
        "*": {
            "Ktpl_Quickview/js/ktpl_config": {
                "productUrl": "<?php echo $productUrl; ?>",
                "buttonText": "<?php echo $buttonText; ?>",
                "isEnabled": "<?php echo $isEnabled; ?>",
                "baseUrl": "<?php echo $baseUrl; ?>",
                "productItemInfo": "<?php echo $productItemInfo; ?>",
                "productImageWrapper": "<?php echo $productImageWrapper; ?>"
            }
        }
    }
</script>
